# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 17:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('logDate', models.DateTimeField(auto_now=True)),
                ('adminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=150, unique=True)),
                ('foundDateTime', models.DateTimeField(blank=True, null=True)),
                ('lastScanDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('siteDescription', models.CharField(max_length=150)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='PersonsPageRank',
            fields=[
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_app.Persons')),
                ('Rank', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'personspagerank',
            },
        ),
        migrations.AddField(
            model_name='persons',
            name='addedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pages',
            name='siteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Sites'),
        ),
        migrations.AddField(
            model_name='keywords',
            name='personID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Persons'),
        ),
        migrations.AddField(
            model_name='personspagerank',
            name='PageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.Pages'),
        ),
    ]
